### PR TITLE
Improve ragel parser to handle postgresql and sqlite3 variations of iso format

### PR DESCRIPTION
**Pull request by funny-falcon**
It improves ragel parser to handle formats returned by this two databases.
With this patch, home_run is just a bit slower than annoying monkey patch for sequel https://gist.github.com/871634

Times on my current machine:

```
~/tmp/ruby-sequel$ ruby seq_home.rb
            user system total real
base 3.760000   0.080000   3.840000 (  3.841594)
~/tmp/ruby-sequel$ ruby seq_home.rb fix
            user system total real
fix 0.870000   0.080000   0.950000 (  0.955666)
~/tmp/ruby-sequel$ ruby seq_home.rb home_run
            user system total real
home_run  1.070000   0.070000   1.140000 (  1.135983)
```

With unpatched home run:

```
~/tmp/ruby-sequel$ ruby seq_home.rb home_run
            user     system      total        real
home_run  2.690000   0.080000   2.770000 (  2.755941)
```

### CODE REVIEW

**Comment by jeremyevans** [comment]
Looks good.  I'll see if I can test and merge this tomorrow, and put out a 1.0.2 gem.  Thanks for the help!

**Comment by jeremyevans** [comment]
Tests well except on JRuby, as the JRuby cext support doesn't include rb_cstr_to_dbl.  I'll see if I can come up with a different implementation so it works on JRuby 1.6.0.

**Comment by funny-falcon** [comment]
Well, initially `atof` was there and worked well. I thought `rb_cstr_to_dbl` would be more portable. It seems that I was mistaken :(

**Comment by jeremyevans** [comment]
I went with atoi/pow, but probably should have used atof.  Anyway, it appears to work.  I also changed to the code to require at least one digit after the decimal, and support up to 9 digits.

**Comment by funny-falcon** [comment]
`atoi` were my first attempt :) well it would be a lesson for me - use first workable solution and do not spend time :)

to require at least one digit - is a good catch.

By the way, please help me with my english: which phrase could also be used with a meaning similar to `is a good catch`?

**Comment by jeremyevans** [comment]
"is a good catch" is probably the most appropriate phrase.  "is a better solution" has a similar meaning.  The difference is that "is a good catch" implies a problem with the existing code, while "is a better solution" doesn't imply a problem. In this case, either would work.  I required at least one digit because I think that's more correct, but all that really happens is it falls back to the pure ruby parser.  Also, the use of atoi requires at least one digit to work correctly, I think.

Don't worry, your English is certainly understandable, and pretty good for a non-native speaker. :)

**Comment by funny-falcon** [comment]
I look to the dictionary often :)

**Pull request merged**
